
title: Retired Replicant
email: replicantretired@gmail.com
description: >-
  A personal blog for synthetic souls.
baseurl: ""
url: "https://retired-replicant.github.io"  # Make sure the URL is correct

theme: null
plugins:
  - jekyll-feed

markdown: kramdown
